name: Deploy AWS
on:
  push:
    branches:
      - main
env:
  REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID}}
  REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID}}
  REACT_APP_PUBLIC_KEY: ${{ secrets.REACT_APP_PUBLIC_KEY}}
  AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SOURCE_DIR: "build"
jobs:
  build:
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
- name: Yarn Install
      run: yarn install
- name: Staging Build
      run: yarn build
- name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete